### ISSUE TITLE
Update cable metod put.

### ISSUE THREAD

**Issue by VictorPavlushin** [Anthony25/python-netboxapi#5] opened 2019-02-22 02:50 UTC
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.5

1. Create cable, Length length_unit do not fill.
2. If use class NetboxMapper in netboxapi and change termination.
3. Сalling the put method, returns an error that length_unit cannot be empty. Even if you first remove the attributes from the object. They are added to the to_dict functions class NetboxMapper. Here is an example of what is being transmitted in json:

> {'id': 612, 'termination_a_type': 'dcim.interface', 'termination_a_id': 10488, 'termination_b_type': 'dcim.interface', 'termination_b_id': 8491, 'type': 3040, 'status': True, 'label': '', 'color': '', 'length': None, 'length_unit': None, 'termination_a': 10488, 'termination_b': 8492}

**Comment by Anthony25** [comment] 2019-03-02 12:20
Thanks a lot for your bug report.
It seems to be more a bug on Netbox than it is on this library. I'll look at their code.

**Comment by VictorPavlushin** [comment] 2019-03-03 06:43
There they still have a problem :(
https://groups.google.com/d/msg/netbox-discuss/nmjePUNCJo8/hgFZRS24BAAJ

**Comment by Anthony25** [comment] 2019-03-05 00:27
Oh but I'm sure it's an issue on the netbox side, as my lib is sending the exact response that netbox sent before, but I have to look at their code to fix it ;)

**Comment by Anthony25** [comment] 2019-03-05 17:53
https://github.com/digitalocean/netbox/pull/2967 should fix it

**Comment by Anthony25** [comment] 2019-03-05 17:56
I'm closing the issue as it's not a bug on this lib, but on Netbox

**Closed by Anthony25** 2019-03-05 17:56 UTC
