### ISSUE TITLE
NetboxMapper return format has changed

### ISSUE THREAD

**Issue by kasimon** [Anthony25/python-netboxapi#2] opened 2018-05-03 12:10 UTC
NetboxMapper objects now return the data inside a results hash, so in order to use them one needs to

    virt_clusters = NetboxMapper(netbox_api, app_name="virtualization", model="clusters")
    clusters = list(virt_clusters.get(name=cluster_name))[0].results

This is a bit clumsy and doesn't match the documentation.

**Comment by Anthony25** [comment] 2018-05-04 17:09
Hi,
It should normally be fixed in [https://github.com/Anthony25/python-netboxapi/tree/dev](https://github.com/Anthony25/python-netboxapi/tree/dev).

Could you test it on your side and tell me if you see any bug in this changes?
Thanks

**Comment by kasimon** [comment] 2018-05-07 09:29
Hi Anthony,
it works better now but now I've discovered that when I use the mapper, search parameters don't seem to get passed to netbox when using the mapper:

    # netbox_api.get('dcim/device-types/?q=ProLiant%20DL380%20G7')
    "GET /netbox/api/dcim/device-types/?q=ProLiant%20DL380%20G7 HTTP/1.1" 200 329 "-" "python-requests/2.18.4"

vs

    # dcim_device_types = NetboxMapper(netbox_api, app_name='dcim', model="device-types")
    # list(dcim_device_types(q='ProLiant%20DL380%20G7'))
    "GET /netbox/api/dcim/device-types/ HTTP/1.1" 200 1121 "-" "python-requests/2.18.4"

I tried to trace down the path of the parameters but failed to find the requests 'method' parameter that you use.

**Comment by Anthony25** [comment] 2018-05-07 10:02
Thanks a lot for the report, I am going to fix it right now.

Really sorry for the bugs you found, I will try to find a way for real integration tests, with a working netbox database.

**Comment by Anthony25** [comment] 2018-05-07 10:09
@kasimon it should be fixed now.

**Comment by kasimon** [comment] 2018-05-07 11:09
No problem, I appreciate your reactivity and am just starting with netbox api myself. But automated tests sound great.

**Comment by Anthony25** [comment] 2018-05-07 11:19
There is already some automated tests ([here](https://travis-ci.org/Anthony25/python-netboxapi)) but they are only unit tests, meaning that I mock every call of the Netbox API. The issue is that if I am wrong about a certain behaviour of the API or if anything changes, unit tests will pass, when an integration test would break.

**Comment by kasimon** [comment] 2018-05-07 11:58
Works great now, thanks!

**Comment by Anthony25** [comment] 2018-05-07 13:10
Thanks a lot, I'm merging it in master ;)

**Closed** 2018-05-07 13:11 UTC
